TIERS = {
    'TIER_1': [
        'Scottie Scheffler',
        'Rory McIlroy',
        'Brooks Koepka',
        'Xander Schauffele',
        'Ludvig Aberg',
        'Jon Rahm',
        'Collin Morikawa',
        'Bryson DeChambeau',
        'Max Homa',
        'Joaquin Niemann',
    ],
    'TIER_2': [
        'Patrick Cantlay',
        'Cameron Smith',
        'Wyndham Clark',
        'Viktor Hovland',
        'Tommy Fleetwood',
        'Justin Thomas',
        'Cameron Young',
        'Hideki Matsuyama',
        'Will Zalatoris',
        'Jason Day',
    ],

    'TIER_3': [
        'Tyrrell Hatton',
        'Dustin Johnson',
        'Jordan Spieth',
        'Matthew Fitzpatrick',
        'Sungjae Im',
        'Sahith Theegala',
        'Tony Finau',
        'Byeong Hun An',
        'Min Woo Lee',
        'Sam Burns',
    ],

    'TIER_4': [
        'Shane Lowry',
        'Talor Gooch',
        'Joohyung Kim',
        'Si Woo Kim',
        'Russell Henley',
        'Corey Conners',
        'Sepp Straka',
        'Adam Scott',
        'Patrick Reed',
        'Akshay Bhatia',
    ],

    'TIER_5': [
        'Dean Burmester',
        'Brian Harman',
        'Rickie Fowler',
        'Alex Noren',
        'Stephan Jaeger',
        'Tiger Woods',
        'Denny McCarthy',
        'Nicolai Hojgaard',
        'Christiaan Bezuidenhout',
        'Keith Mitchell',
    ],

    'TIER_6': [
        'Cameron Davis',
        'Billy Horschel',
        'Harris English',
        'Chris Kirk',
        'J.T. Poston',
        'Jake Knapp',
        'Taylor Pendrith',
        'Keegan Bradley',
        'Kurt Kitayama',
        'Adrian Meronk',
        'Adam Schenk',
        'Lucas Herbert',
        'Mackenzie Hughes',
        'Tom Hoge',
        'Aaron Rai',
        'Phil Mickelson',
        'Thomas Detry',
        'Eric Cole',
        'Lucas Glover',
        'Justin Rose',
        'Matthieu Pavon',
        'Ryan Fox',
        'Erik van Rooyen',
        'Nick Taylor',
        'Adam Hadwin',
        'Taylor Moore',
        'Nick Dunlap',
        'Robert MacIntyre',
        'Beau Hossler',
        'Austin Eckroat',
        'David Puig',
        'Maverick McNealy',
        'Sebastian Soderberg',
        'Andrew Putnam',
        'Luke List',
        'Ben Griffin',
        'Thorbjørn Olesen',
        'Patrick Rodgers',
        'Rasmus Hojgaard',
        'Keita Nakajima',
        'Victor Perez',
        'Adrian Otaegui',
        'Matt Wallace',
        'Brendon Todd',
        'Jordan L. Smith',
        'Emiliano Grillo',
        'Kyoung-Hoon Lee',
        'Alex Smalley',
        'Christopher Gotterup',
        'Gary Woodland',
        'Mark Hubbard',
        'Doug Ghim',
        'Adam Svensson',
        'Seonghyun Kim',
        'Tim Widing',
        'Takumi Kanaya',
        'Ryo Hisatsune',
        'Lee Hodges',
        'Alex Björk',
        'Charley Hoffman',
        'Peter Malnati',
        'Francesco Molinari',
        'Ben Kohles',
        'Alejandro Tosti',
        'Andy Ogletree',
        'Thirston Lawrence',
        'Sami Valimaki',
        'Vincent Norrman',
        'Padraig Harrington',
        'Brice Garnett',
        'Grayson Murray',
        'Martin Kaymer',
        'Camilo Villegas',
        'Zac Blair',
        'Jimmy Walker',
        'Luke Donald',
        'Michael Block',
        'Jason Dufner',
        'Y.E. Yang',
        'Andrew Svoboda',
        'Jesse Mueller',
        'Jared Jones',
        'Zac Oakely',
        'Kyle Mendoza',
        'Tyler Collet',
        'Larkin Gross',
        'Brad Marek',
        'Josh Speight',
        'John Somers',
        'Jeremy Wells',
        'Braden Shattuck',
        'Wyatt Worthington',
        'John Daly',
        'Shaun Micheel',
        'Rich Beem',
        'Jesper Svensson',
        'C.T. Pan',
        'Ryan Van Velzen',
        'Josh Bevell',
        'Evan Bowser',
        'Preston Cole',
        'Jeffrey Kellen',
        'Kazuma Kobori',
        'Tracy Phillips',
        'Matt Dobyns',
        'Ben Polland',
    ],

}
