TIERS = {
    'TIER_1': [
        'Scottie Scheffler',
        'Rory McIlroy',
        'Xander Schauffele',
        'Collin Morikawa',
        'Viktor Hovland',
        'Bryson DeChambeau',
        'Ludvig Aberg',
        'Brooks Koepka',
        'Tommy Fleetwood',
    ],
    'TIER_2': [
        'Justin Thomas',
        'Cameron Smith',
        'Matt Fitzpatrick',
        'Max Homa',
        'Hideki Matsuyama',
        'Patrick Cantlay',
        'Tony Finau',
        'Sahith Theegala',
        'Tyrrell Hatton',
        'Wyndham Clark',
    ],

    'TIER_3': [
        'Sam Burns',
        'Tom Kim',
        'Jordan Spieth',
        'Shane Lowry',
        'Min Woo Lee',
        'Corey Conners',
        'Dustin Johnson',
        'Sungjae Im',
        'Cameron Young',
        'Keegan Bradley',
    ],

    'TIER_4': [
        'Will Zalatoris',
        'Jason Day',
        'Russell Henley',
        'Sepp Straka',
        'Robert MacIntyre',
        'Si Woo Kim',
        'Dean Burmester',
        'Byeong Hun An',
        'Alex Noren',
        'Brian Harman',
    ],

    'TIER_5': [
        'Adam Scott',
        'Christiaan Bezuidenhout',
        'Billy Horschel',
        'Justin Rose',
        'Denny McCarthy',
        'Harris English',
        'Sergio Garcia',
        'Adam Hadwin',
        'Aaron Rai',
        'Rickie Fowler',
    ],

    'TIER_6': [
        'Akshay Bhatia',
        'Thomas Detry',
        'Tom Hoge',
        'Ryan Fox',
        'Victor Perez',
        'Austin Eckroat',
        'Kurt Kitayama',
        'Lucas Glover',
        'Adrian Meronk',
        'Nicolai Hojgaard',
        'J.T. Poston',
        'Mackenzie Hughes',
        'Erik van Rooyen',
        'Stephan Jaeger',
        'Chris Kirk',
        'Tiger Woods',
        'Taylor Moore',
        'Cameron Davis',
        'Eric Cole',
        'Tom McKibbin',
        'Taylor Pendrith',
        'Beau Hossler',
        'Daniel Berger',
        'Matthieu Pavon',
        'Jake Knapp',
        'Mark Hubbard',
        'Davis Thompson',
        'David Puig',
        'Phil Mickelson',
        'Webb Simpson',
        'Seamus Power',
        'Nick Dunlap',
        'Nick Taylor',
        'Emiliano Grillo',
        'Martin Kaymer',
        'Adam Schenk',
        'Brendon Todd',
        'Adam Svensson',
        'Tim Widing',
        'Harry Higgs',
        'Justin Lower',
        'Gary Woodland',
        'Greyson Sigg',
        'Chesson Hadley',
        'Matt Kuchar',
        'Richard Mansell',
        'Mac Meissner',
        'Matteo Manassero',
        'Seonghyun Kim',
        'Takumi Kanaya',
        'Ben Kohles',
        'Rikuya Hoshino',
        'Frankie Capan',
        'Peter Malnati',
        'Zac Blair',
        'Rico Hoey',
        'Brandon Wu',
        'Isaiah Salinda',
        'Brian Campbell',
        'Sam Bennett',
        'Gordon Sargent',
        'Benjamin James',
        'Max Greyserman',
        'Sam Bairstow',
        'Ryo Ishikawa',
        'Francesco Molinari',
        'Maxwell Moldovan',
        'Brendan Valdes',
        'Luke Clanton',
        'Nicolas Echavarria',
        'Carter Jenkins',
        'Eugenio Lopez-Chacarra',
        'Grant Forrest',
        'Taisei Shimizu',
        'Edoardo Molinari',
        'Jason Scrivener',
        'Robert Rock',
        'Riki Kawamoto',
        'Brandon Robinson-Thompson',
        'Logan McAllister',
        'Sung Kang',
        'Jim Herman',
        'John Chin',
        'Andrew Svoboda',
        'Stewart Hagestad',
        'Charles Reiter',
        'Michael McGowan',
        'Jackson Suber',
        'Casey Jarvis',
        'Christopher Petefish',
        'Chris Naegel',
        'Joey Vrzich',
        'Omar Morales',
        'Santiago De La Fuente',
        'Carson Schaake',
        'Willie Mack',
        'Colin Prater',
        'Hiroshi Tai',
        'Wells Williams',
        'Otto Black',
        'Bryan Kim',
        'Frederik Kjettrup',
        'Neal Shipley',
        'Ashton McCulloch',
        'Parker Bell',
        'Gunnar Broin',
        'Jackson Buchanan',
    ],

}
